-- Index supporting the prune engine's expiry scan.
--
-- Expiry is evaluated against a blob's last-access time, falling back to its
-- upload time when it has never been accessed. The accessed.timestamp column
-- already has an index from 001_initial.sql, but blobs.uploaded did not, so
-- the never-accessed half of that predicate forced a full table scan of blobs
-- on every prune cycle. On a 1.07M blob store this took the prune query from
-- 573ms down to 1ms.
--
-- Note for future migrations: the runner in client.ts splits files on the
-- statement separator without parsing comments, so putting that character in
-- a comment silently cuts the statement in half.
CREATE INDEX IF NOT EXISTS blobs_uploaded ON blobs (uploaded);
