name: Nix

on:
  push:
  pull_request:

jobs:
  flake-check:
    name: Flake Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check flake
        run: bash nix/check.sh
